language: php

sudo: false

php:
  - 7.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - pecl install ds
  - mkdir -p build-logs
  - composer install --prefer-source --no-interaction

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

notifications:
  email: false

script:
  - make test
  - make coverage

after_success:
  - travis_retry php vendor/bin/coveralls
