language: php

sudo: false

php:
  - 7.1
  - nightly

before_script:
  - composer install --prefer-source --no-interaction

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

script: make test
