language: php

sudo: false

php:
  - 7.1
  - nightly

before_script:
  - pecl install ds
  - php -d extension=ds.so
  - composer install --prefer-source --no-interaction

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

script: make test
